x-deploy-policy: &x-deploy-policy
  replicas: 1
  update_config:
    parallelism: 1
    delay: 30s
    order: stop-first
    failure_action: rollback
  rollback_config:
    parallelism: 1
    delay: 30s
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 120s

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    env_file: .env
    environment:
      - GF_LOG_LEVEL=info
    networks:
      - dockerswarm_monitoring
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - grafana-init
    deploy: *x-deploy-policy
    logging: *x-default-logging

volumes:
  grafana:
    external: true

networks:
  dockerswarm_monitoring:
    name: dockerswarm_monitoring
    external: true
