dbs:
  - path: /var/lib/grafana/grafana.db
    replicas:
      - type: s3
        endpoint: "${LITESTREAM_REPLICA_ENDPOINT}"
        bucket: "${LITESTREAM_REPLICA_BUCKET}"
        region: "${LITESTREAM_REPLICA_REGION}"
        access-key-id: "${LITESTREAM_ACCESS_KEY_ID}"
        secret-access-key: "${LITESTREAM_SECRET_ACCESS_KEY}"
        force-path-style: true

        # Specifies how often new snapshots will be created.
        # This is used to reduce the time to restore since newer snapshots will have fewer WAL frames to apply.
        # Retention still applies to these snapshots.
        # 
        # If you do not set a snapshot interval then a new snapshot will be created whenever retention is performed.
        # Retention occurs every 24 hours by default.
        snapshot-interval: 24h
